### ISSUE TITLE
Scheme Src (Main Swagger File)

### ISSUE THREAD

**Issue by thebruce** [schemepunk/schema-got-swagger#2]
- [x] Figure out how to not use tokenization - use options.named = false
- [x] Add options switch to move us into template Object stuff instead of file loading the templates in transform
- [x] Add way to pass in templateObject at schemePunk instantiation and at schemePunk runner instantiation
- [x] Within transform we need to render partials and either pass that along as the value as a string or json (can borrow that from current implementation) or render the partials withing the destination template.
- [x] Within transform we need to be able to specify the rendering of only a specific partial and turn off and on the destination template
- [x] Write tests for new processing and transform options
- [x] PR this on schemepunk
- [x] Upgrade schemepunk into schemagot swagger and then write tests for each partial we've written for swagger main file
- [x] Transform " to ' for Json parse in final file.
- [x] See how we do on the entire file render by writing render example using example data file with template object.
- [x] Write flow for schemaSrc
- [x] Write schema for schemaSrc
- [x] Write validation for schemeSrc Objects
- [x] Write schemePunkScheme defaults yaml for schemeSrc processing swagger 2.0
- [x] Write validation for schemePunkScheme coming in 
- [x] Use semver realizations along with the defaults for the template or any provided templating - create a function that uses the semverRealizations and creates an object with those paths and the object we pass along (and names it).
- [x] Write reusable function to examine if we should use a default for a config/template and populate a semverist realization or if the user has passed in their own either single file or semverist shape. Use these realizations along with the defaults for the default schemePunk or any provided schemePunk when no options are passed in || only a default is passed in for templates, and schemes
- [x] Implement the above function for mainSwaggerFile templates
- [x] Implement the above function for schemes for the main Swagger file.
- [x] Write setSchemeSrcOptions function in index using configurator
- [ ] Validate schemeSrcOptions
- [x] Validate swaggerTemplates coming in as one template used as default or in semverist shape
- [x] Write code to add templates and holdover values for the current api version in the realized schemePunkScheme for all desiredRealizations
- [x] Write code to run schemePunk schemes using passed in templates and provided swagger main data files for all versions of the API provided.
- [x] Write tests for schemeSrc using defaults with a semverist shaped schemeSrc object.

**Comment by thebruce** [comment]
related https://github.com/schemepunk/scheme-punk/pull/115

**Comment by patrickocoffeyo** [comment]
related https://github.com/schemepunk/schema-got-swagger/pull/4
